# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Openzeppelin
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: 'openzeppelin/yarn.lock'

      - name: NPM CI
        run: |
          cd openzeppelin
          yarn
      - name: test
        run: |
          cd openzeppelin
          npx hardhat test
