# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Openzeppelin CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  HARDHAT_VAR_ALCHEMY_API_KEY: ${{ secrets.HARDHAT_VAR_ALCHEMY_API_KEY }}
  HARDHAT_VAR_ETHERSCAN_API_KEY: ${{ secrets.HARDHAT_VAR_ETHERSCAN_API_KEY }}
  HARDHAT_VAR_SEPOLIA_TEST_NET_PRIVATE_KEY: ${{ secrets.HARDHAT_VAR_SEPOLIA_TEST_NET_PRIVATE_KEY }}
  HARDHAT_VAR_SEPOLIA_ACCOUNT: ${{ secrets.HARDHAT_VAR_SEPOLIA_ACCOUNT }}

jobs:
  Openzeppelin:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: 'openzeppelin/yarn.lock'

      - name: Yarn
        run: |
          cd openzeppelin
          yarn

      - name: Test
        run: |
          cd openzeppelin
          npx hardhat test
